### Create token

POST http://localhost:3000/api/auth/authenticate
content-type: application/json

{
	"username": "linvi",
	"password": "password"
}

### Verify authentication token

GET http://localhost:3000/api/auth/verify
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODZlZTU1NDkwZTJlMzFhYTAxNTM5M2IiLCJpYXQiOjE0ODM2NjQ4NDksImV4cCI6MTQ4MzY2NjI4OX0.WOXEgnaWsrpP17qJThjRmT20YkQe8j9-xFNhF0zwf1I

### Invalidate authentication token

POST http://localhost:3000/api/auth/invalidate
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODZlZTU1NDkwZTJlMzFhYTAxNTM5M2IiLCJpYXQiOjE0ODM2NjQ4NDksImV4cCI6MTQ4MzY2NjI4OX0.WOXEgnaWsrpP17qJThjRmT20YkQe8j9-xFNhF0zwf1I